version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - email-validation-net
    volumes:
      - ./backend:/app
    container_name: email-verifier-backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - email-validation-net
