version: '3.6'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - email-validator-net
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - email-validator-net
    depends_on:
      - backend

networks:
  email-validator-net:
    driver: bridge
