name: Docker Build and Push

on:
  push:
    branches:
      - main  # 触发条件，可以选择推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker-compose -f docker-compose.yml push
